COMMENT=		web services.

V=			0.1
DISTNAME=		www-$V
CATEGORIES=		net

HOMEPAGE=		https://pz.do
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes
SITES=			https://pz.do/ftp/releases/

NO_TEST=		Yes

PREFIX=			${VARBASE}

.include <bsd.port.mk>
