COMMENT=		web services.

GH_PROJECT=		pz
GH_ACCOUNT=		josegpt
GH_TAGNAME=		0.7

CATEGORIES=		www
HOMEPAGE=		https://pz.do
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

NO_TEST=		Yes

PREFIX=			${VARBASE}

.include <bsd.port.mk>
