COMMENT=		etc.

V=			0.2
DISTNAME=		etc-$V
CATEGORIES=		net

HOMEPAGE=		https://github.com/josegpt/etc
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes
SITES=			https://pz.do/ftp/releases/

NO_BUILD=		Yes
NO_TEST=		Yes

PREFIX=			${SYSCONFDIR}

.include <bsd.port.mk>
